#!/usr/bin/env bash
set -euo pipefail
SCRIPT_PATH=$(realpath -e -- "$0")
SCRIPT_DIR="${SCRIPT_PATH%/*}"
source "$SCRIPT_DIR"/.venv/bin/activate
"$SCRIPT_DIR"/.venv/bin/python "$SCRIPT_DIR"/"${SCRIPT_PATH##*/}".py "$@"
#fin
